data:
  dataset_dir: data
  batch_size: 8
  num_workers: 4
  pos_enc_rrwp:
    ksteps: 16
  target_col: 'score'

model:
  grit:
    hidden_size: 64
    layers_pre_mp: 0
    n_layers: 2
    n_heads: 2
    dropout: 0.3
    attn_dropout: 0.5


train: # Training params
  device: 'cuda'                    # device to use for training
  max_epochs: 100                 # *total number of epochs
  use_amp: False          # whether to use torch.amp for automatic mixed precision training
  task_type: classification             # task type, 'classification' or 'regression'
  learning_rate: 0.0005        # *learning rate
  lr_patience: 5
  lr_decay: 0.5
  min_lr: 1e-6
  weight_decay: 0.
